# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html
{% set version = "0.0.1" %}
{% set build = "1" %}

package:
  name: mining-d
  version: {{ version }}

about:
  home: https://github.com/vinnub/MINING-D
  summary: Infer D genes from antibody repertoire sequence data

source:
  git_url: https://github.com/ShawHahnLab/MINING-D.git
  git_branch: conda
  git_depth: 1

build:
  number: {{ build }}
  script: mkdir -p $PREFIX/bin && install MINING_D.py $PREFIX/bin/

requirements:
  run:
    - python=3.6.5
    - biopython
    - networkx<2.4
    - joblib
    - numpy
    - scipy
    - click
